version: '3.8'

services:
  memgpt-mcp:
    build:
      context: .
    container_name: memgpt-mcp
    ports:
      - "8050:8050"
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./memgpt_data:/app/data
    restart: unless-stopped
